[workspace]
members = [
    "anchor-transaction",
    "cli",
    "cli-config",
    "extra-signers",
    "faucet",
    "localnet",
    "rpc",
    "serde-pubkey-str",
    "transaction",
]
resolver = "2"

[workspace.dependencies]
anchor-cli = "0.27.0"
anchor-lang = "0.28.0"
anchor-client = "0.28.0"
anchor-spl = "0.28.0"
anchor-syn = { version = "0.28.0", features = ["idl", "hash"] }
solana-client = "1.16"
solana-faucet = "1.16"
solana-program = "1.16"
solana-sdk = "1.16"
solana-account-decoder = "1.16"
solana-remote-wallet = "1.16"
solana-transaction-status = "1.16"
solana-clap-v3-utils = "1.16"
solana-cli-config = "1.16"
solana-version = "1.16"
spl-token = "3.2"
spl-associated-token-account = "1.1.2"
clap = { version = "3", features = [ "derive", "env" ] }
spl-token-faucet = { version = "0.0.1", git = "https://github.com/paul-schaaf/spl-token-faucet.git" }
spl-memo = "3"