[package]
name = "solana-devtools-signers"
version = "0.1.0"
edition = "2021"
description = "An assortment of useful signer types for Solana development"

[[example]]
name = "usb"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
solana-sdk = "1.14.11"
solana-program = "1.14.11"
solana-remote-wallet = "1.14.11"
solana-clap-v3-utils = "1.14.11"
uriparse = "0.6.4"
