[package]
name = "solana-devtools-pubkey"
version = "0.2.0"
edition = "2021"

[dependencies]
solana-sdk = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
