[package]
name = "solana-devtools-cli-config"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
solana-sdk = { workspace = true }
solana-clap-v3-utils = { workspace = true }
solana-cli-config = { workspace = true }
clap = { workspace = true }
