[package]
name = "solana-devtools-tx"
version = "0.26.0"
edition = "2021"

[features]
anchor = [
    "anchor-lang"
]

[dependencies]
solana-sdk = "1.14"
bincode = "1.3.3"
anchor-lang = { version = "0.27.0", optional = true }

[dev-dependencies]
spl-memo = "3.0.1"
